name: Push on Epitech repository

on:
  push:
    branches:
      - '*'

jobs:
  build:
    if: github.repository == 'Killian-Vienne/T-SEC-902'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_TOKEN }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout $CI_COMMIT_REF_NAME
          git push --repo="git@github.com:EpitechMscProPromo2025/T-SEC-902-TLS_1.git" --force

      # - name: Push Wiki
      #   run: |
      #     git clone "git@github.com:EpitechMscProPromo2025/T-SEC-902-TLS_1.wiki.git" wiki
      #     cd wiki
      #     git remote add epitech "git@github.com:EpitechMscProPromo2025/T-SEC-902-TLS_1.wiki.git"
      #     git push epitech --force

